### PR TITLE
Clarification for github template

### PR DESCRIPTION
**Pull request by Bohaska**
most people don't know the difference between the 2 sections listed in the balancing/feedback template, so I clarified it.

### CODE REVIEW

**Review by itcannotbe — COMMENTED** [review]
Most feedback made isn't even about a problem.

Also I don't get it why they even get it wrong.

**Comment by Bohaska** [comment]
> Most feedback made isn't even about a problem.

What is it about?

**Comment by itcannotbe** [comment]
> > Most feedback made isn't even about a problem.
> 
> What is it about?

Quality of life mostly.

**Comment by Bohaska** [comment]
in that case "the problem" is the inconvenience of a feature

**Comment by Anuken** [comment]
This is unnecessary.

**Comment by Bohaska** [comment]
it died a brutal death... but it was necessary.

**Pull request closed without merging**
